<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240704191717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE frais_scolaires_frais_scolarites (frais_scolaires_id INT NOT NULL, frais_scolarites_id INT NOT NULL, INDEX IDX_DDB628D3D031BFA8 (frais_scolaires_id), INDEX IDX_DDB628D35C8EF115 (frais_scolarites_id), PRIMARY KEY(frais_scolaires_id, frais_scolarites_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE frais_scolaires_annee_scolaires (frais_scolaires_id INT NOT NULL, annee_scolaires_id INT NOT NULL, INDEX IDX_37275413D031BFA8 (frais_scolaires_id), INDEX IDX_37275413E639FDE4 (annee_scolaires_id), PRIMARY KEY(frais_scolaires_id, annee_scolaires_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redoublements3 (id INT AUTO_INCREMENT NOT NULL, niveau_id INT NOT NULL, redoublement2_id INT NOT NULL, scolarite1_id INT DEFAULT NULL, scolarite2_id INT DEFAULT NULL, scolarite3_id INT DEFAULT NULL, INDEX IDX_CB5A8C85B3E9C81 (niveau_id), INDEX IDX_CB5A8C857FA60213 (redoublement2_id), INDEX IDX_CB5A8C85F4C45000 (scolarite1_id), INDEX IDX_CB5A8C85E671FFEE (scolarite2_id), INDEX IDX_CB5A8C855ECD988B (scolarite3_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE frais_scolaires_frais_scolarites ADD CONSTRAINT FK_DDB628D3D031BFA8 FOREIGN KEY (frais_scolaires_id) REFERENCES frais_scolaires (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE frais_scolaires_frais_scolarites ADD CONSTRAINT FK_DDB628D35C8EF115 FOREIGN KEY (frais_scolarites_id) REFERENCES frais_scolarites (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE frais_scolaires_annee_scolaires ADD CONSTRAINT FK_37275413D031BFA8 FOREIGN KEY (frais_scolaires_id) REFERENCES frais_scolaires (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE frais_scolaires_annee_scolaires ADD CONSTRAINT FK_37275413E639FDE4 FOREIGN KEY (annee_scolaires_id) REFERENCES annee_scolaires (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE redoublements3 ADD CONSTRAINT FK_CB5A8C85B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('ALTER TABLE redoublements3 ADD CONSTRAINT FK_CB5A8C857FA60213 FOREIGN KEY (redoublement2_id) REFERENCES redoublements2 (id)');
        $this->addSql('ALTER TABLE redoublements3 ADD CONSTRAINT FK_CB5A8C85F4C45000 FOREIGN KEY (scolarite1_id) REFERENCES scolarites1 (id)');
        $this->addSql('ALTER TABLE redoublements3 ADD CONSTRAINT FK_CB5A8C85E671FFEE FOREIGN KEY (scolarite2_id) REFERENCES scolarites2 (id)');
        $this->addSql('ALTER TABLE redoublements3 ADD CONSTRAINT FK_CB5A8C855ECD988B FOREIGN KEY (scolarite3_id) REFERENCES scolarites3 (id)');
        $this->addSql('ALTER TABLE annee_scolaires ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD annee_debut INT NOT NULL, ADD annee_fin INT NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE annee_scolaires ADD CONSTRAINT FK_B7252347B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE annee_scolaires ADD CONSTRAINT FK_B7252347896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_B7252347B03A8386 ON annee_scolaires (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B7252347896DBBDE ON annee_scolaires (updated_by_id)');
        $this->addSql('ALTER TABLE caisses ADD scolarite_id INT DEFAULT NULL, ADD author_id INT NOT NULL, ADD annee_scolaires_id INT NOT NULL, ADD date_op DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD libelle VARCHAR(100) NOT NULL, ADD debit DOUBLE PRECISION DEFAULT NULL, ADD credit DOUBLE PRECISION DEFAULT NULL, ADD solde DOUBLE PRECISION NOT NULL, ADD solde_cumul DOUBLE PRECISION NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE caisses ADD CONSTRAINT FK_8E0326DAAA6B2AB6 FOREIGN KEY (scolarite_id) REFERENCES frais_scolarites (id)');
        $this->addSql('ALTER TABLE caisses ADD CONSTRAINT FK_8E0326DAF675F31B FOREIGN KEY (author_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE caisses ADD CONSTRAINT FK_8E0326DAE639FDE4 FOREIGN KEY (annee_scolaires_id) REFERENCES annee_scolaires (id)');
        $this->addSql('CREATE INDEX IDX_8E0326DAAA6B2AB6 ON caisses (scolarite_id)');
        $this->addSql('CREATE INDEX IDX_8E0326DAF675F31B ON caisses (author_id)');
        $this->addSql('CREATE INDEX IDX_8E0326DAE639FDE4 ON caisses (annee_scolaires_id)');
        $this->addSql('ALTER TABLE cercles ADD region_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE cercles ADD CONSTRAINT FK_45C1718D98260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE cercles ADD CONSTRAINT FK_45C1718DB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE cercles ADD CONSTRAINT FK_45C1718D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_45C1718D8947610D ON cercles (designation)');
        $this->addSql('CREATE INDEX IDX_45C1718D98260155 ON cercles (region_id)');
        $this->addSql('CREATE INDEX IDX_45C1718DB03A8386 ON cercles (created_by_id)');
        $this->addSql('CREATE INDEX IDX_45C1718D896DBBDE ON cercles (updated_by_id)');
        $this->addSql('ALTER TABLE classes ADD niveau_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD capacite INT NOT NULL, ADD effectif INT DEFAULT NULL, ADD disponibilite INT NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE classes ADD CONSTRAINT FK_2ED7EC5B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('ALTER TABLE classes ADD CONSTRAINT FK_2ED7EC5B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE classes ADD CONSTRAINT FK_2ED7EC5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2ED7EC58947610D ON classes (designation)');
        $this->addSql('CREATE INDEX IDX_2ED7EC5B3E9C81 ON classes (niveau_id)');
        $this->addSql('CREATE INDEX IDX_2ED7EC5B03A8386 ON classes (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2ED7EC5896DBBDE ON classes (updated_by_id)');
        $this->addSql('ALTER TABLE communes ADD cercle_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE communes ADD CONSTRAINT FK_5C5EE2A527413AB9 FOREIGN KEY (cercle_id) REFERENCES cercles (id)');
        $this->addSql('ALTER TABLE communes ADD CONSTRAINT FK_5C5EE2A5B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE communes ADD CONSTRAINT FK_5C5EE2A5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_5C5EE2A527413AB9 ON communes (cercle_id)');
        $this->addSql('CREATE INDEX IDX_5C5EE2A5B03A8386 ON communes (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5C5EE2A5896DBBDE ON communes (updated_by_id)');
        $this->addSql('ALTER TABLE cycles ADD enseignement_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE cycles ADD CONSTRAINT FK_72B88B24ABEC3B20 FOREIGN KEY (enseignement_id) REFERENCES enseignements (id)');
        $this->addSql('ALTER TABLE cycles ADD CONSTRAINT FK_72B88B24B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE cycles ADD CONSTRAINT FK_72B88B24896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_72B88B24ABEC3B20 ON cycles (enseignement_id)');
        $this->addSql('CREATE INDEX IDX_72B88B24B03A8386 ON cycles (created_by_id)');
        $this->addSql('CREATE INDEX IDX_72B88B24896DBBDE ON cycles (updated_by_id)');
        $this->addSql('ALTER TABLE departements ADD cycle_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE departements ADD CONSTRAINT FK_CF7489B25EC1162 FOREIGN KEY (cycle_id) REFERENCES cycles (id)');
        $this->addSql('ALTER TABLE departements ADD CONSTRAINT FK_CF7489B2B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE departements ADD CONSTRAINT FK_CF7489B2896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_CF7489B25EC1162 ON departements (cycle_id)');
        $this->addSql('CREATE INDEX IDX_CF7489B2B03A8386 ON departements (created_by_id)');
        $this->addSql('CREATE INDEX IDX_CF7489B2896DBBDE ON departements (updated_by_id)');
        $this->addSql('ALTER TABLE departs ADD eleve_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD date_depart DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD motif VARCHAR(255) DEFAULT NULL, ADD ecole_destination VARCHAR(255) DEFAULT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE departs ADD CONSTRAINT FK_15CE7982A6CC7B2 FOREIGN KEY (eleve_id) REFERENCES eleves (id)');
        $this->addSql('ALTER TABLE departs ADD CONSTRAINT FK_15CE7982B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE departs ADD CONSTRAINT FK_15CE7982896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_15CE7982A6CC7B2 ON departs (eleve_id)');
        $this->addSql('CREATE INDEX IDX_15CE7982B03A8386 ON departs (created_by_id)');
        $this->addSql('CREATE INDEX IDX_15CE7982896DBBDE ON departs (updated_by_id)');
        $this->addSql('ALTER TABLE details_caisses ADD caisse_id INT NOT NULL, ADD author_id INT NOT NULL, ADD date_op DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD designation VARCHAR(100) NOT NULL, ADD montant DOUBLE PRECISION NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE details_caisses ADD CONSTRAINT FK_68505FCB27B4FEBF FOREIGN KEY (caisse_id) REFERENCES caisses (id)');
        $this->addSql('ALTER TABLE details_caisses ADD CONSTRAINT FK_68505FCBF675F31B FOREIGN KEY (author_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_68505FCB27B4FEBF ON details_caisses (caisse_id)');
        $this->addSql('CREATE INDEX IDX_68505FCBF675F31B ON details_caisses (author_id)');
        $this->addSql('ALTER TABLE dossier_eleves ADD eleves_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(255) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE dossier_eleves ADD CONSTRAINT FK_D04A5D98C2140342 FOREIGN KEY (eleves_id) REFERENCES eleves (id)');
        $this->addSql('ALTER TABLE dossier_eleves ADD CONSTRAINT FK_D04A5D98B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE dossier_eleves ADD CONSTRAINT FK_D04A5D98896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_D04A5D98C2140342 ON dossier_eleves (eleves_id)');
        $this->addSql('CREATE INDEX IDX_D04A5D98B03A8386 ON dossier_eleves (created_by_id)');
        $this->addSql('CREATE INDEX IDX_D04A5D98896DBBDE ON dossier_eleves (updated_by_id)');
        $this->addSql('ALTER TABLE echeances ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD echeance DATETIME NOT NULL, ADD periode VARCHAR(50) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE echeances ADD CONSTRAINT FK_AA45FFA6B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE echeances ADD CONSTRAINT FK_AA45FFA6896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_AA45FFA6B03A8386 ON echeances (created_by_id)');
        $this->addSql('CREATE INDEX IDX_AA45FFA6896DBBDE ON echeances (updated_by_id)');
        $this->addSql('ALTER TABLE ecole_provenances ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD adresse VARCHAR(255) DEFAULT NULL, ADD telephone VARCHAR(25) DEFAULT NULL, ADD email VARCHAR(255) DEFAULT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE ecole_provenances ADD CONSTRAINT FK_59378F8CB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ecole_provenances ADD CONSTRAINT FK_59378F8C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_59378F8CB03A8386 ON ecole_provenances (created_by_id)');
        $this->addSql('CREATE INDEX IDX_59378F8C896DBBDE ON ecole_provenances (updated_by_id)');
        $this->addSql('ALTER TABLE eleves ADD nom_id INT NOT NULL, ADD prenom_id INT NOT NULL, ADD lieu_naissance_id INT NOT NULL, ADD classe_id INT NOT NULL, ADD statut_id INT NOT NULL, ADD ecole_an_dernier_id INT DEFAULT NULL, ADD ecole_recrutement_id INT NOT NULL, ADD departement_id INT NOT NULL, ADD scolarite1_id INT DEFAULT NULL, ADD scolarite2_id INT DEFAULT NULL, ADD scolarite3_id INT DEFAULT NULL, ADD redoublement1_id INT DEFAULT NULL, ADD redoublement2_id INT DEFAULT NULL, ADD redoublement3_id INT DEFAULT NULL, ADD user_id INT DEFAULT NULL, ADD parent_id INT NOT NULL, ADD frais_scolarite_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD image_name VARCHAR(255) DEFAULT NULL, ADD matricule VARCHAR(50) NOT NULL, ADD sexe VARCHAR(8) NOT NULL, ADD statut_finance VARCHAR(8) NOT NULL, ADD date_naissance DATE NOT NULL, ADD date_extrait DATE NOT NULL, ADD num_extrait VARCHAR(30) NOT NULL, ADD is_admis TINYINT(1) NOT NULL, ADD is_actif TINYINT(1) NOT NULL, ADD is_handicap TINYINT(1) NOT NULL, ADD nature_handicap VARCHAR(50) DEFAULT NULL, ADD date_inscription DATE NOT NULL, ADD date_recrutement DATE NOT NULL, ADD fullname VARCHAR(255) NOT NULL, ADD adresse VARCHAR(255) DEFAULT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1C8121CE9 FOREIGN KEY (nom_id) REFERENCES noms (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B158819F9E FOREIGN KEY (prenom_id) REFERENCES prenoms (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B138C8067D FOREIGN KEY (lieu_naissance_id) REFERENCES lieu_naissances (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B18F5EA509 FOREIGN KEY (classe_id) REFERENCES classes (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1F6203804 FOREIGN KEY (statut_id) REFERENCES statuts (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B18D3AF34D FOREIGN KEY (ecole_an_dernier_id) REFERENCES ecole_provenances (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B180BDEBFF FOREIGN KEY (ecole_recrutement_id) REFERENCES ecole_provenances (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1CCF9E01E FOREIGN KEY (departement_id) REFERENCES departements (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1F4C45000 FOREIGN KEY (scolarite1_id) REFERENCES scolarites1 (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1E671FFEE FOREIGN KEY (scolarite2_id) REFERENCES scolarites2 (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B15ECD988B FOREIGN KEY (scolarite3_id) REFERENCES scolarites3 (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B16D13ADFD FOREIGN KEY (redoublement1_id) REFERENCES redoublements1 (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B17FA60213 FOREIGN KEY (redoublement2_id) REFERENCES redoublements2 (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1C71A6576 FOREIGN KEY (redoublement3_id) REFERENCES redoublements3 (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1727ACA70 FOREIGN KEY (parent_id) REFERENCES parents (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1F40B33B5 FOREIGN KEY (frais_scolarite_id) REFERENCES frais_scolarites (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE eleves ADD CONSTRAINT FK_383B09B1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_383B09B1C8121CE9 ON eleves (nom_id)');
        $this->addSql('CREATE INDEX IDX_383B09B158819F9E ON eleves (prenom_id)');
        $this->addSql('CREATE INDEX IDX_383B09B138C8067D ON eleves (lieu_naissance_id)');
        $this->addSql('CREATE INDEX IDX_383B09B18F5EA509 ON eleves (classe_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1F6203804 ON eleves (statut_id)');
        $this->addSql('CREATE INDEX IDX_383B09B18D3AF34D ON eleves (ecole_an_dernier_id)');
        $this->addSql('CREATE INDEX IDX_383B09B180BDEBFF ON eleves (ecole_recrutement_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1CCF9E01E ON eleves (departement_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1F4C45000 ON eleves (scolarite1_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1E671FFEE ON eleves (scolarite2_id)');
        $this->addSql('CREATE INDEX IDX_383B09B15ECD988B ON eleves (scolarite3_id)');
        $this->addSql('CREATE INDEX IDX_383B09B16D13ADFD ON eleves (redoublement1_id)');
        $this->addSql('CREATE INDEX IDX_383B09B17FA60213 ON eleves (redoublement2_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1C71A6576 ON eleves (redoublement3_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_383B09B1A76ED395 ON eleves (user_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1727ACA70 ON eleves (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_383B09B1F40B33B5 ON eleves (frais_scolarite_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1B03A8386 ON eleves (created_by_id)');
        $this->addSql('CREATE INDEX IDX_383B09B1896DBBDE ON eleves (updated_by_id)');
        $this->addSql('ALTER TABLE enseignements ADD etablissement_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE enseignements ADD CONSTRAINT FK_89D79280FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissements (id)');
        $this->addSql('ALTER TABLE enseignements ADD CONSTRAINT FK_89D79280B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE enseignements ADD CONSTRAINT FK_89D79280896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_89D79280FF631228 ON enseignements (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_89D79280B03A8386 ON enseignements (created_by_id)');
        $this->addSql('CREATE INDEX IDX_89D79280896DBBDE ON enseignements (updated_by_id)');
        $this->addSql('ALTER TABLE etablissements ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD forme_juridique VARCHAR(150) NOT NULL, ADD adresse VARCHAR(255) NOT NULL, ADD num_decision_creation VARCHAR(60) NOT NULL, ADD num_decision_ouverture VARCHAR(60) NOT NULL, ADD date_ouverture DATE DEFAULT NULL, ADD num_social VARCHAR(60) DEFAULT NULL, ADD num_fiscal VARCHAR(60) NOT NULL, ADD telephone VARCHAR(25) NOT NULL, ADD telephone_mobile VARCHAR(25) DEFAULT NULL, ADD cpte_bancaire VARCHAR(100) DEFAULT NULL, ADD email VARCHAR(255) DEFAULT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE etablissements ADD CONSTRAINT FK_29F65EB1B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE etablissements ADD CONSTRAINT FK_29F65EB1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_29F65EB1B03A8386 ON etablissements (created_by_id)');
        $this->addSql('CREATE INDEX IDX_29F65EB1896DBBDE ON etablissements (updated_by_id)');
        $this->addSql('ALTER TABLE frais_scolaires ADD echeance_id INT NOT NULL, ADD frais_type_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD montant INT NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE frais_scolaires ADD CONSTRAINT FK_45A17205B318673 FOREIGN KEY (echeance_id) REFERENCES echeances (id)');
        $this->addSql('ALTER TABLE frais_scolaires ADD CONSTRAINT FK_45A1720C8B377BF FOREIGN KEY (frais_type_id) REFERENCES frais_type (id)');
        $this->addSql('ALTER TABLE frais_scolaires ADD CONSTRAINT FK_45A1720B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE frais_scolaires ADD CONSTRAINT FK_45A1720896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_45A17205B318673 ON frais_scolaires (echeance_id)');
        $this->addSql('CREATE INDEX IDX_45A1720C8B377BF ON frais_scolaires (frais_type_id)');
        $this->addSql('CREATE INDEX IDX_45A1720B03A8386 ON frais_scolaires (created_by_id)');
        $this->addSql('CREATE INDEX IDX_45A1720896DBBDE ON frais_scolaires (updated_by_id)');
        $this->addSql('ALTER TABLE frais_scolarites ADD annee_scolaires_id INT NOT NULL, ADD frais_type_id INT NOT NULL, ADD montant INT NOT NULL, ADD arrieres INT NOT NULL, ADD inscription INT NOT NULL, ADD carnet INT NOT NULL, ADD transfert INT NOT NULL, ADD septembre INT NOT NULL, ADD octobre INT NOT NULL, ADD novembre INT NOT NULL, ADD decembre INT NOT NULL, ADD janvier INT NOT NULL, ADD fevrier INT NOT NULL, ADD mars INT NOT NULL, ADD avril INT NOT NULL, ADD mai INT NOT NULL, ADD juin INT NOT NULL, ADD autre INT NOT NULL, ADD echeance_transfert DATETIME DEFAULT NULL, ADD echeance_carnet DATETIME DEFAULT NULL, ADD echeance_inscription DATETIME DEFAULT NULL, ADD echeances_arrieres DATETIME DEFAULT NULL, ADD echeance_septembre DATETIME NOT NULL, ADD echeance_octobre DATETIME NOT NULL, ADD echeance_novembre DATETIME NOT NULL, ADD echeance_decembre DATETIME NOT NULL, ADD echeance_janvier DATETIME NOT NULL, ADD echeance_fevrier DATETIME NOT NULL, ADD echeance_mars DATETIME NOT NULL, ADD echeance_avril DATETIME NOT NULL, ADD echeance_mai DATETIME NOT NULL, ADD echeance_juin DATETIME NOT NULL, ADD echeance_autre DATETIME NOT NULL');
        $this->addSql('ALTER TABLE frais_scolarites ADD CONSTRAINT FK_B130BF49E639FDE4 FOREIGN KEY (annee_scolaires_id) REFERENCES annee_scolaires (id)');
        $this->addSql('ALTER TABLE frais_scolarites ADD CONSTRAINT FK_B130BF49C8B377BF FOREIGN KEY (frais_type_id) REFERENCES frais_type (id)');
        $this->addSql('CREATE INDEX IDX_B130BF49E639FDE4 ON frais_scolarites (annee_scolaires_id)');
        $this->addSql('CREATE INDEX IDX_B130BF49C8B377BF ON frais_scolarites (frais_type_id)');
        $this->addSql('ALTER TABLE frais_type ADD statut_id INT NOT NULL, ADD niveau_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD periode VARCHAR(50) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE frais_type ADD CONSTRAINT FK_7926F141F6203804 FOREIGN KEY (statut_id) REFERENCES statuts (id)');
        $this->addSql('ALTER TABLE frais_type ADD CONSTRAINT FK_7926F141B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('ALTER TABLE frais_type ADD CONSTRAINT FK_7926F141B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE frais_type ADD CONSTRAINT FK_7926F141896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_7926F141F6203804 ON frais_type (statut_id)');
        $this->addSql('CREATE INDEX IDX_7926F141B3E9C81 ON frais_type (niveau_id)');
        $this->addSql('CREATE INDEX IDX_7926F141B03A8386 ON frais_type (created_by_id)');
        $this->addSql('CREATE INDEX IDX_7926F141896DBBDE ON frais_type (updated_by_id)');
        $this->addSql('ALTER TABLE lieu_naissances ADD commune_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE lieu_naissances ADD CONSTRAINT FK_49F8927F131A4F72 FOREIGN KEY (commune_id) REFERENCES communes (id)');
        $this->addSql('ALTER TABLE lieu_naissances ADD CONSTRAINT FK_49F8927FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE lieu_naissances ADD CONSTRAINT FK_49F8927F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_49F8927F131A4F72 ON lieu_naissances (commune_id)');
        $this->addSql('CREATE INDEX IDX_49F8927FB03A8386 ON lieu_naissances (created_by_id)');
        $this->addSql('CREATE INDEX IDX_49F8927F896DBBDE ON lieu_naissances (updated_by_id)');
        $this->addSql('ALTER TABLE meres ADD nom_id INT NOT NULL, ADD prenom_id INT NOT NULL, ADD profession_id INT NOT NULL, ADD telephone_id INT DEFAULT NULL, ADD nina_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD fullname VARCHAR(255) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408AC8121CE9 FOREIGN KEY (nom_id) REFERENCES noms (id)');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408A58819F9E FOREIGN KEY (prenom_id) REFERENCES prenoms (id)');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408AFDEF8996 FOREIGN KEY (profession_id) REFERENCES professions (id)');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408AFE649A29 FOREIGN KEY (telephone_id) REFERENCES telephones (id)');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408A5586F33C FOREIGN KEY (nina_id) REFERENCES ninas (id)');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408AB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE meres ADD CONSTRAINT FK_2D8B408A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_2D8B408AC8121CE9 ON meres (nom_id)');
        $this->addSql('CREATE INDEX IDX_2D8B408A58819F9E ON meres (prenom_id)');
        $this->addSql('CREATE INDEX IDX_2D8B408AFDEF8996 ON meres (profession_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8B408AFE649A29 ON meres (telephone_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8B408A5586F33C ON meres (nina_id)');
        $this->addSql('CREATE INDEX IDX_2D8B408AB03A8386 ON meres (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2D8B408A896DBBDE ON meres (updated_by_id)');
        $this->addSql('ALTER TABLE ninas ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(15) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE ninas ADD CONSTRAINT FK_51AD1AF2B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ninas ADD CONSTRAINT FK_51AD1AF2896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_51AD1AF2B03A8386 ON ninas (created_by_id)');
        $this->addSql('CREATE INDEX IDX_51AD1AF2896DBBDE ON ninas (updated_by_id)');
        $this->addSql('ALTER TABLE niveaux ADD cycle_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE niveaux ADD CONSTRAINT FK_56F771A05EC1162 FOREIGN KEY (cycle_id) REFERENCES cycles (id)');
        $this->addSql('ALTER TABLE niveaux ADD CONSTRAINT FK_56F771A0B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE niveaux ADD CONSTRAINT FK_56F771A0896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_56F771A05EC1162 ON niveaux (cycle_id)');
        $this->addSql('CREATE INDEX IDX_56F771A0B03A8386 ON niveaux (created_by_id)');
        $this->addSql('CREATE INDEX IDX_56F771A0896DBBDE ON niveaux (updated_by_id)');
        $this->addSql('ALTER TABLE noms CHANGE designation designation VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE parents ADD pere_id INT NOT NULL, ADD mere_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE parents ADD CONSTRAINT FK_FD501D6A3FD73900 FOREIGN KEY (pere_id) REFERENCES peres (id)');
        $this->addSql('ALTER TABLE parents ADD CONSTRAINT FK_FD501D6A39DEC40E FOREIGN KEY (mere_id) REFERENCES meres (id)');
        $this->addSql('ALTER TABLE parents ADD CONSTRAINT FK_FD501D6AB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE parents ADD CONSTRAINT FK_FD501D6A896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_FD501D6A3FD73900 ON parents (pere_id)');
        $this->addSql('CREATE INDEX IDX_FD501D6A39DEC40E ON parents (mere_id)');
        $this->addSql('CREATE INDEX IDX_FD501D6AB03A8386 ON parents (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FD501D6A896DBBDE ON parents (updated_by_id)');
        $this->addSql('ALTER TABLE peres ADD nom_id INT NOT NULL, ADD prenom_id INT NOT NULL, ADD profession_id INT NOT NULL, ADD telephone_id INT NOT NULL, ADD nina_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD fullname VARCHAR(255) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B9C8121CE9 FOREIGN KEY (nom_id) REFERENCES noms (id)');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B958819F9E FOREIGN KEY (prenom_id) REFERENCES prenoms (id)');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B9FDEF8996 FOREIGN KEY (profession_id) REFERENCES professions (id)');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B9FE649A29 FOREIGN KEY (telephone_id) REFERENCES telephones (id)');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B95586F33C FOREIGN KEY (nina_id) REFERENCES ninas (id)');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B9B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE peres ADD CONSTRAINT FK_B5FB13B9896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_B5FB13B9C8121CE9 ON peres (nom_id)');
        $this->addSql('CREATE INDEX IDX_B5FB13B958819F9E ON peres (prenom_id)');
        $this->addSql('CREATE INDEX IDX_B5FB13B9FDEF8996 ON peres (profession_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B5FB13B9FE649A29 ON peres (telephone_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B5FB13B95586F33C ON peres (nina_id)');
        $this->addSql('CREATE INDEX IDX_B5FB13B9B03A8386 ON peres (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B5FB13B9896DBBDE ON peres (updated_by_id)');
        $this->addSql('ALTER TABLE prenoms CHANGE designation designation VARCHAR(150) NOT NULL');
        $this->addSql('ALTER TABLE professions ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE professions ADD CONSTRAINT FK_2FDA85FAB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE professions ADD CONSTRAINT FK_2FDA85FA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_2FDA85FAB03A8386 ON professions (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2FDA85FA896DBBDE ON professions (updated_by_id)');
        $this->addSql('ALTER TABLE redoublements1 ADD niveau_id INT NOT NULL, ADD scolarite1_id INT DEFAULT NULL, ADD scolarite2_id INT DEFAULT NULL, ADD scolarite3_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE redoublements1 ADD CONSTRAINT FK_2554EDA9B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('ALTER TABLE redoublements1 ADD CONSTRAINT FK_2554EDA9F4C45000 FOREIGN KEY (scolarite1_id) REFERENCES scolarites1 (id)');
        $this->addSql('ALTER TABLE redoublements1 ADD CONSTRAINT FK_2554EDA9E671FFEE FOREIGN KEY (scolarite2_id) REFERENCES scolarites2 (id)');
        $this->addSql('ALTER TABLE redoublements1 ADD CONSTRAINT FK_2554EDA95ECD988B FOREIGN KEY (scolarite3_id) REFERENCES scolarites3 (id)');
        $this->addSql('CREATE INDEX IDX_2554EDA9B3E9C81 ON redoublements1 (niveau_id)');
        $this->addSql('CREATE INDEX IDX_2554EDA9F4C45000 ON redoublements1 (scolarite1_id)');
        $this->addSql('CREATE INDEX IDX_2554EDA9E671FFEE ON redoublements1 (scolarite2_id)');
        $this->addSql('CREATE INDEX IDX_2554EDA95ECD988B ON redoublements1 (scolarite3_id)');
        $this->addSql('ALTER TABLE redoublements2 ADD niveau_id INT NOT NULL, ADD redoublement1_id INT NOT NULL, ADD scolarite1_id INT DEFAULT NULL, ADD scolarite2_id INT DEFAULT NULL, ADD scolarite3_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE redoublements2 ADD CONSTRAINT FK_BC5DBC13B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('ALTER TABLE redoublements2 ADD CONSTRAINT FK_BC5DBC136D13ADFD FOREIGN KEY (redoublement1_id) REFERENCES redoublements1 (id)');
        $this->addSql('ALTER TABLE redoublements2 ADD CONSTRAINT FK_BC5DBC13F4C45000 FOREIGN KEY (scolarite1_id) REFERENCES scolarites1 (id)');
        $this->addSql('ALTER TABLE redoublements2 ADD CONSTRAINT FK_BC5DBC13E671FFEE FOREIGN KEY (scolarite2_id) REFERENCES scolarites2 (id)');
        $this->addSql('ALTER TABLE redoublements2 ADD CONSTRAINT FK_BC5DBC135ECD988B FOREIGN KEY (scolarite3_id) REFERENCES scolarites3 (id)');
        $this->addSql('CREATE INDEX IDX_BC5DBC13B3E9C81 ON redoublements2 (niveau_id)');
        $this->addSql('CREATE INDEX IDX_BC5DBC136D13ADFD ON redoublements2 (redoublement1_id)');
        $this->addSql('CREATE INDEX IDX_BC5DBC13F4C45000 ON redoublements2 (scolarite1_id)');
        $this->addSql('CREATE INDEX IDX_BC5DBC13E671FFEE ON redoublements2 (scolarite2_id)');
        $this->addSql('CREATE INDEX IDX_BC5DBC135ECD988B ON redoublements2 (scolarite3_id)');
        $this->addSql('ALTER TABLE regions ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE regions ADD CONSTRAINT FK_A26779F3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE regions ADD CONSTRAINT FK_A26779F3896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_A26779F3B03A8386 ON regions (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A26779F3896DBBDE ON regions (updated_by_id)');
        $this->addSql('ALTER TABLE santes ADD eleve_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD maladie VARCHAR(255) NOT NULL, ADD medecin VARCHAR(50) DEFAULT NULL, ADD numero_urgence VARCHAR(25) NOT NULL, ADD centre_sante VARCHAR(150) DEFAULT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE santes ADD CONSTRAINT FK_C1A17FE9A6CC7B2 FOREIGN KEY (eleve_id) REFERENCES eleves (id)');
        $this->addSql('ALTER TABLE santes ADD CONSTRAINT FK_C1A17FE9B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE santes ADD CONSTRAINT FK_C1A17FE9896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_C1A17FE9A6CC7B2 ON santes (eleve_id)');
        $this->addSql('CREATE INDEX IDX_C1A17FE9B03A8386 ON santes (created_by_id)');
        $this->addSql('CREATE INDEX IDX_C1A17FE9896DBBDE ON santes (updated_by_id)');
        $this->addSql('ALTER TABLE scolarites1 ADD niveau_id INT NOT NULL, ADD scolarite INT NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE scolarites1 ADD CONSTRAINT FK_328D2B44B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('CREATE INDEX IDX_328D2B44B3E9C81 ON scolarites1 (niveau_id)');
        $this->addSql('ALTER TABLE scolarites2 ADD scolarite1_id INT NOT NULL, ADD niveau_id INT NOT NULL, ADD scolarite INT NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE scolarites2 ADD CONSTRAINT FK_AB847AFEF4C45000 FOREIGN KEY (scolarite1_id) REFERENCES scolarites1 (id)');
        $this->addSql('ALTER TABLE scolarites2 ADD CONSTRAINT FK_AB847AFEB3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('CREATE INDEX IDX_AB847AFEF4C45000 ON scolarites2 (scolarite1_id)');
        $this->addSql('CREATE INDEX IDX_AB847AFEB3E9C81 ON scolarites2 (niveau_id)');
        $this->addSql('ALTER TABLE scolarites3 ADD niveau_id INT NOT NULL, ADD scolarite INT NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE scolarites3 ADD CONSTRAINT FK_DC834A68B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('CREATE INDEX IDX_DC834A68B3E9C81 ON scolarites3 (niveau_id)');
        $this->addSql('ALTER TABLE statuts ADD niveau_id INT NOT NULL, ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD designation VARCHAR(150) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE statuts ADD CONSTRAINT FK_403505E6B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveaux (id)');
        $this->addSql('ALTER TABLE statuts ADD CONSTRAINT FK_403505E6B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE statuts ADD CONSTRAINT FK_403505E6896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_403505E6B3E9C81 ON statuts (niveau_id)');
        $this->addSql('CREATE INDEX IDX_403505E6B03A8386 ON statuts (created_by_id)');
        $this->addSql('CREATE INDEX IDX_403505E6896DBBDE ON statuts (updated_by_id)');
        $this->addSql('ALTER TABLE telephones ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD numero VARCHAR(25) NOT NULL, ADD created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ADD slug VARCHAR(128) NOT NULL');
        $this->addSql('ALTER TABLE telephones ADD CONSTRAINT FK_6FCD09FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE telephones ADD CONSTRAINT FK_6FCD09F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_6FCD09FB03A8386 ON telephones (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6FCD09F896DBBDE ON telephones (updated_by_id)');
        $this->addSql('ALTER TABLE users ADD nom_id INT NOT NULL, ADD prenom_id INT NOT NULL, ADD reset_token VARCHAR(100) DEFAULT NULL, CHANGE fullname fullname VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9C8121CE9 FOREIGN KEY (nom_id) REFERENCES noms (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E958819F9E FOREIGN KEY (prenom_id) REFERENCES prenoms (id)');
        $this->addSql('CREATE INDEX IDX_1483A5E9C8121CE9 ON users (nom_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E958819F9E ON users (prenom_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1C71A6576');
        $this->addSql('ALTER TABLE frais_scolaires_frais_scolarites DROP FOREIGN KEY FK_DDB628D3D031BFA8');
        $this->addSql('ALTER TABLE frais_scolaires_frais_scolarites DROP FOREIGN KEY FK_DDB628D35C8EF115');
        $this->addSql('ALTER TABLE frais_scolaires_annee_scolaires DROP FOREIGN KEY FK_37275413D031BFA8');
        $this->addSql('ALTER TABLE frais_scolaires_annee_scolaires DROP FOREIGN KEY FK_37275413E639FDE4');
        $this->addSql('ALTER TABLE redoublements3 DROP FOREIGN KEY FK_CB5A8C85B3E9C81');
        $this->addSql('ALTER TABLE redoublements3 DROP FOREIGN KEY FK_CB5A8C857FA60213');
        $this->addSql('ALTER TABLE redoublements3 DROP FOREIGN KEY FK_CB5A8C85F4C45000');
        $this->addSql('ALTER TABLE redoublements3 DROP FOREIGN KEY FK_CB5A8C85E671FFEE');
        $this->addSql('ALTER TABLE redoublements3 DROP FOREIGN KEY FK_CB5A8C855ECD988B');
        $this->addSql('DROP TABLE frais_scolaires_frais_scolarites');
        $this->addSql('DROP TABLE frais_scolaires_annee_scolaires');
        $this->addSql('DROP TABLE redoublements3');
        $this->addSql('ALTER TABLE annee_scolaires DROP FOREIGN KEY FK_B7252347B03A8386');
        $this->addSql('ALTER TABLE annee_scolaires DROP FOREIGN KEY FK_B7252347896DBBDE');
        $this->addSql('DROP INDEX IDX_B7252347B03A8386 ON annee_scolaires');
        $this->addSql('DROP INDEX IDX_B7252347896DBBDE ON annee_scolaires');
        $this->addSql('ALTER TABLE annee_scolaires DROP created_by_id, DROP updated_by_id, DROP annee_debut, DROP annee_fin, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE caisses DROP FOREIGN KEY FK_8E0326DAAA6B2AB6');
        $this->addSql('ALTER TABLE caisses DROP FOREIGN KEY FK_8E0326DAF675F31B');
        $this->addSql('ALTER TABLE caisses DROP FOREIGN KEY FK_8E0326DAE639FDE4');
        $this->addSql('DROP INDEX IDX_8E0326DAAA6B2AB6 ON caisses');
        $this->addSql('DROP INDEX IDX_8E0326DAF675F31B ON caisses');
        $this->addSql('DROP INDEX IDX_8E0326DAE639FDE4 ON caisses');
        $this->addSql('ALTER TABLE caisses DROP scolarite_id, DROP author_id, DROP annee_scolaires_id, DROP date_op, DROP libelle, DROP debit, DROP credit, DROP solde, DROP solde_cumul, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE cercles DROP FOREIGN KEY FK_45C1718D98260155');
        $this->addSql('ALTER TABLE cercles DROP FOREIGN KEY FK_45C1718DB03A8386');
        $this->addSql('ALTER TABLE cercles DROP FOREIGN KEY FK_45C1718D896DBBDE');
        $this->addSql('DROP INDEX UNIQ_45C1718D8947610D ON cercles');
        $this->addSql('DROP INDEX IDX_45C1718D98260155 ON cercles');
        $this->addSql('DROP INDEX IDX_45C1718DB03A8386 ON cercles');
        $this->addSql('DROP INDEX IDX_45C1718D896DBBDE ON cercles');
        $this->addSql('ALTER TABLE cercles DROP region_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE classes DROP FOREIGN KEY FK_2ED7EC5B3E9C81');
        $this->addSql('ALTER TABLE classes DROP FOREIGN KEY FK_2ED7EC5B03A8386');
        $this->addSql('ALTER TABLE classes DROP FOREIGN KEY FK_2ED7EC5896DBBDE');
        $this->addSql('DROP INDEX UNIQ_2ED7EC58947610D ON classes');
        $this->addSql('DROP INDEX IDX_2ED7EC5B3E9C81 ON classes');
        $this->addSql('DROP INDEX IDX_2ED7EC5B03A8386 ON classes');
        $this->addSql('DROP INDEX IDX_2ED7EC5896DBBDE ON classes');
        $this->addSql('ALTER TABLE classes DROP niveau_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP capacite, DROP effectif, DROP disponibilite, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE communes DROP FOREIGN KEY FK_5C5EE2A527413AB9');
        $this->addSql('ALTER TABLE communes DROP FOREIGN KEY FK_5C5EE2A5B03A8386');
        $this->addSql('ALTER TABLE communes DROP FOREIGN KEY FK_5C5EE2A5896DBBDE');
        $this->addSql('DROP INDEX IDX_5C5EE2A527413AB9 ON communes');
        $this->addSql('DROP INDEX IDX_5C5EE2A5B03A8386 ON communes');
        $this->addSql('DROP INDEX IDX_5C5EE2A5896DBBDE ON communes');
        $this->addSql('ALTER TABLE communes DROP cercle_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE cycles DROP FOREIGN KEY FK_72B88B24ABEC3B20');
        $this->addSql('ALTER TABLE cycles DROP FOREIGN KEY FK_72B88B24B03A8386');
        $this->addSql('ALTER TABLE cycles DROP FOREIGN KEY FK_72B88B24896DBBDE');
        $this->addSql('DROP INDEX IDX_72B88B24ABEC3B20 ON cycles');
        $this->addSql('DROP INDEX IDX_72B88B24B03A8386 ON cycles');
        $this->addSql('DROP INDEX IDX_72B88B24896DBBDE ON cycles');
        $this->addSql('ALTER TABLE cycles DROP enseignement_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE departements DROP FOREIGN KEY FK_CF7489B25EC1162');
        $this->addSql('ALTER TABLE departements DROP FOREIGN KEY FK_CF7489B2B03A8386');
        $this->addSql('ALTER TABLE departements DROP FOREIGN KEY FK_CF7489B2896DBBDE');
        $this->addSql('DROP INDEX IDX_CF7489B25EC1162 ON departements');
        $this->addSql('DROP INDEX IDX_CF7489B2B03A8386 ON departements');
        $this->addSql('DROP INDEX IDX_CF7489B2896DBBDE ON departements');
        $this->addSql('ALTER TABLE departements DROP cycle_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE departs DROP FOREIGN KEY FK_15CE7982A6CC7B2');
        $this->addSql('ALTER TABLE departs DROP FOREIGN KEY FK_15CE7982B03A8386');
        $this->addSql('ALTER TABLE departs DROP FOREIGN KEY FK_15CE7982896DBBDE');
        $this->addSql('DROP INDEX IDX_15CE7982A6CC7B2 ON departs');
        $this->addSql('DROP INDEX IDX_15CE7982B03A8386 ON departs');
        $this->addSql('DROP INDEX IDX_15CE7982896DBBDE ON departs');
        $this->addSql('ALTER TABLE departs DROP eleve_id, DROP created_by_id, DROP updated_by_id, DROP date_depart, DROP motif, DROP ecole_destination, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE details_caisses DROP FOREIGN KEY FK_68505FCB27B4FEBF');
        $this->addSql('ALTER TABLE details_caisses DROP FOREIGN KEY FK_68505FCBF675F31B');
        $this->addSql('DROP INDEX IDX_68505FCB27B4FEBF ON details_caisses');
        $this->addSql('DROP INDEX IDX_68505FCBF675F31B ON details_caisses');
        $this->addSql('ALTER TABLE details_caisses DROP caisse_id, DROP author_id, DROP date_op, DROP designation, DROP montant, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE frais_scolaires DROP FOREIGN KEY FK_45A17205B318673');
        $this->addSql('ALTER TABLE frais_scolaires DROP FOREIGN KEY FK_45A1720C8B377BF');
        $this->addSql('ALTER TABLE frais_scolaires DROP FOREIGN KEY FK_45A1720B03A8386');
        $this->addSql('ALTER TABLE frais_scolaires DROP FOREIGN KEY FK_45A1720896DBBDE');
        $this->addSql('DROP INDEX IDX_45A17205B318673 ON frais_scolaires');
        $this->addSql('DROP INDEX IDX_45A1720C8B377BF ON frais_scolaires');
        $this->addSql('DROP INDEX IDX_45A1720B03A8386 ON frais_scolaires');
        $this->addSql('DROP INDEX IDX_45A1720896DBBDE ON frais_scolaires');
        $this->addSql('ALTER TABLE frais_scolaires DROP echeance_id, DROP frais_type_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP montant, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B9C8121CE9');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B958819F9E');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B9FDEF8996');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B9FE649A29');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B95586F33C');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B9B03A8386');
        $this->addSql('ALTER TABLE peres DROP FOREIGN KEY FK_B5FB13B9896DBBDE');
        $this->addSql('DROP INDEX IDX_B5FB13B9C8121CE9 ON peres');
        $this->addSql('DROP INDEX IDX_B5FB13B958819F9E ON peres');
        $this->addSql('DROP INDEX IDX_B5FB13B9FDEF8996 ON peres');
        $this->addSql('DROP INDEX UNIQ_B5FB13B9FE649A29 ON peres');
        $this->addSql('DROP INDEX UNIQ_B5FB13B95586F33C ON peres');
        $this->addSql('DROP INDEX IDX_B5FB13B9B03A8386 ON peres');
        $this->addSql('DROP INDEX IDX_B5FB13B9896DBBDE ON peres');
        $this->addSql('ALTER TABLE peres DROP nom_id, DROP prenom_id, DROP profession_id, DROP telephone_id, DROP nina_id, DROP created_by_id, DROP updated_by_id, DROP fullname, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE dossier_eleves DROP FOREIGN KEY FK_D04A5D98C2140342');
        $this->addSql('ALTER TABLE dossier_eleves DROP FOREIGN KEY FK_D04A5D98B03A8386');
        $this->addSql('ALTER TABLE dossier_eleves DROP FOREIGN KEY FK_D04A5D98896DBBDE');
        $this->addSql('DROP INDEX IDX_D04A5D98C2140342 ON dossier_eleves');
        $this->addSql('DROP INDEX IDX_D04A5D98B03A8386 ON dossier_eleves');
        $this->addSql('DROP INDEX IDX_D04A5D98896DBBDE ON dossier_eleves');
        $this->addSql('ALTER TABLE dossier_eleves DROP eleves_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE echeances DROP FOREIGN KEY FK_AA45FFA6B03A8386');
        $this->addSql('ALTER TABLE echeances DROP FOREIGN KEY FK_AA45FFA6896DBBDE');
        $this->addSql('DROP INDEX IDX_AA45FFA6B03A8386 ON echeances');
        $this->addSql('DROP INDEX IDX_AA45FFA6896DBBDE ON echeances');
        $this->addSql('ALTER TABLE echeances DROP created_by_id, DROP updated_by_id, DROP echeance, DROP periode, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE ecole_provenances DROP FOREIGN KEY FK_59378F8CB03A8386');
        $this->addSql('ALTER TABLE ecole_provenances DROP FOREIGN KEY FK_59378F8C896DBBDE');
        $this->addSql('DROP INDEX IDX_59378F8CB03A8386 ON ecole_provenances');
        $this->addSql('DROP INDEX IDX_59378F8C896DBBDE ON ecole_provenances');
        $this->addSql('ALTER TABLE ecole_provenances DROP created_by_id, DROP updated_by_id, DROP designation, DROP adresse, DROP telephone, DROP email, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1C8121CE9');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B158819F9E');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B138C8067D');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B18F5EA509');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1F6203804');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B18D3AF34D');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B180BDEBFF');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1CCF9E01E');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1F4C45000');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1E671FFEE');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B15ECD988B');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B16D13ADFD');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B17FA60213');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1A76ED395');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1727ACA70');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1F40B33B5');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1B03A8386');
        $this->addSql('ALTER TABLE eleves DROP FOREIGN KEY FK_383B09B1896DBBDE');
        $this->addSql('DROP INDEX IDX_383B09B1C8121CE9 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B158819F9E ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B138C8067D ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B18F5EA509 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1F6203804 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B18D3AF34D ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B180BDEBFF ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1CCF9E01E ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1F4C45000 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1E671FFEE ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B15ECD988B ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B16D13ADFD ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B17FA60213 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1C71A6576 ON eleves');
        $this->addSql('DROP INDEX UNIQ_383B09B1A76ED395 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1727ACA70 ON eleves');
        $this->addSql('DROP INDEX UNIQ_383B09B1F40B33B5 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1B03A8386 ON eleves');
        $this->addSql('DROP INDEX IDX_383B09B1896DBBDE ON eleves');
        $this->addSql('ALTER TABLE eleves DROP nom_id, DROP prenom_id, DROP lieu_naissance_id, DROP classe_id, DROP statut_id, DROP ecole_an_dernier_id, DROP ecole_recrutement_id, DROP departement_id, DROP scolarite1_id, DROP scolarite2_id, DROP scolarite3_id, DROP redoublement1_id, DROP redoublement2_id, DROP redoublement3_id, DROP user_id, DROP parent_id, DROP frais_scolarite_id, DROP created_by_id, DROP updated_by_id, DROP image_name, DROP matricule, DROP sexe, DROP statut_finance, DROP date_naissance, DROP date_extrait, DROP num_extrait, DROP is_admis, DROP is_actif, DROP is_handicap, DROP nature_handicap, DROP date_inscription, DROP date_recrutement, DROP fullname, DROP adresse, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE enseignements DROP FOREIGN KEY FK_89D79280FF631228');
        $this->addSql('ALTER TABLE enseignements DROP FOREIGN KEY FK_89D79280B03A8386');
        $this->addSql('ALTER TABLE enseignements DROP FOREIGN KEY FK_89D79280896DBBDE');
        $this->addSql('DROP INDEX IDX_89D79280FF631228 ON enseignements');
        $this->addSql('DROP INDEX IDX_89D79280B03A8386 ON enseignements');
        $this->addSql('DROP INDEX IDX_89D79280896DBBDE ON enseignements');
        $this->addSql('ALTER TABLE enseignements DROP etablissement_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE etablissements DROP FOREIGN KEY FK_29F65EB1B03A8386');
        $this->addSql('ALTER TABLE etablissements DROP FOREIGN KEY FK_29F65EB1896DBBDE');
        $this->addSql('DROP INDEX IDX_29F65EB1B03A8386 ON etablissements');
        $this->addSql('DROP INDEX IDX_29F65EB1896DBBDE ON etablissements');
        $this->addSql('ALTER TABLE etablissements DROP created_by_id, DROP updated_by_id, DROP designation, DROP forme_juridique, DROP adresse, DROP num_decision_creation, DROP num_decision_ouverture, DROP date_ouverture, DROP num_social, DROP num_fiscal, DROP telephone, DROP telephone_mobile, DROP cpte_bancaire, DROP email, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE prenoms CHANGE designation designation VARCHAR(75) NOT NULL');
        $this->addSql('ALTER TABLE frais_scolarites DROP FOREIGN KEY FK_B130BF49E639FDE4');
        $this->addSql('ALTER TABLE frais_scolarites DROP FOREIGN KEY FK_B130BF49C8B377BF');
        $this->addSql('DROP INDEX IDX_B130BF49E639FDE4 ON frais_scolarites');
        $this->addSql('DROP INDEX IDX_B130BF49C8B377BF ON frais_scolarites');
        $this->addSql('ALTER TABLE frais_scolarites DROP annee_scolaires_id, DROP frais_type_id, DROP montant, DROP arrieres, DROP inscription, DROP carnet, DROP transfert, DROP septembre, DROP octobre, DROP novembre, DROP decembre, DROP janvier, DROP fevrier, DROP mars, DROP avril, DROP mai, DROP juin, DROP autre, DROP echeance_transfert, DROP echeance_carnet, DROP echeance_inscription, DROP echeances_arrieres, DROP echeance_septembre, DROP echeance_octobre, DROP echeance_novembre, DROP echeance_decembre, DROP echeance_janvier, DROP echeance_fevrier, DROP echeance_mars, DROP echeance_avril, DROP echeance_mai, DROP echeance_juin, DROP echeance_autre');
        $this->addSql('ALTER TABLE frais_type DROP FOREIGN KEY FK_7926F141F6203804');
        $this->addSql('ALTER TABLE frais_type DROP FOREIGN KEY FK_7926F141B3E9C81');
        $this->addSql('ALTER TABLE frais_type DROP FOREIGN KEY FK_7926F141B03A8386');
        $this->addSql('ALTER TABLE frais_type DROP FOREIGN KEY FK_7926F141896DBBDE');
        $this->addSql('DROP INDEX IDX_7926F141F6203804 ON frais_type');
        $this->addSql('DROP INDEX IDX_7926F141B3E9C81 ON frais_type');
        $this->addSql('DROP INDEX IDX_7926F141B03A8386 ON frais_type');
        $this->addSql('DROP INDEX IDX_7926F141896DBBDE ON frais_type');
        $this->addSql('ALTER TABLE frais_type DROP statut_id, DROP niveau_id, DROP created_by_id, DROP updated_by_id, DROP periode, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE lieu_naissances DROP FOREIGN KEY FK_49F8927F131A4F72');
        $this->addSql('ALTER TABLE lieu_naissances DROP FOREIGN KEY FK_49F8927FB03A8386');
        $this->addSql('ALTER TABLE lieu_naissances DROP FOREIGN KEY FK_49F8927F896DBBDE');
        $this->addSql('DROP INDEX IDX_49F8927F131A4F72 ON lieu_naissances');
        $this->addSql('DROP INDEX IDX_49F8927FB03A8386 ON lieu_naissances');
        $this->addSql('DROP INDEX IDX_49F8927F896DBBDE ON lieu_naissances');
        $this->addSql('ALTER TABLE lieu_naissances DROP commune_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408AC8121CE9');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408A58819F9E');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408AFDEF8996');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408AFE649A29');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408A5586F33C');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408AB03A8386');
        $this->addSql('ALTER TABLE meres DROP FOREIGN KEY FK_2D8B408A896DBBDE');
        $this->addSql('DROP INDEX IDX_2D8B408AC8121CE9 ON meres');
        $this->addSql('DROP INDEX IDX_2D8B408A58819F9E ON meres');
        $this->addSql('DROP INDEX IDX_2D8B408AFDEF8996 ON meres');
        $this->addSql('DROP INDEX UNIQ_2D8B408AFE649A29 ON meres');
        $this->addSql('DROP INDEX UNIQ_2D8B408A5586F33C ON meres');
        $this->addSql('DROP INDEX IDX_2D8B408AB03A8386 ON meres');
        $this->addSql('DROP INDEX IDX_2D8B408A896DBBDE ON meres');
        $this->addSql('ALTER TABLE meres DROP nom_id, DROP prenom_id, DROP profession_id, DROP telephone_id, DROP nina_id, DROP created_by_id, DROP updated_by_id, DROP fullname, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE professions DROP FOREIGN KEY FK_2FDA85FAB03A8386');
        $this->addSql('ALTER TABLE professions DROP FOREIGN KEY FK_2FDA85FA896DBBDE');
        $this->addSql('DROP INDEX IDX_2FDA85FAB03A8386 ON professions');
        $this->addSql('DROP INDEX IDX_2FDA85FA896DBBDE ON professions');
        $this->addSql('ALTER TABLE professions DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE redoublements1 DROP FOREIGN KEY FK_2554EDA9B3E9C81');
        $this->addSql('ALTER TABLE redoublements1 DROP FOREIGN KEY FK_2554EDA9F4C45000');
        $this->addSql('ALTER TABLE redoublements1 DROP FOREIGN KEY FK_2554EDA9E671FFEE');
        $this->addSql('ALTER TABLE redoublements1 DROP FOREIGN KEY FK_2554EDA95ECD988B');
        $this->addSql('DROP INDEX IDX_2554EDA9B3E9C81 ON redoublements1');
        $this->addSql('DROP INDEX IDX_2554EDA9F4C45000 ON redoublements1');
        $this->addSql('DROP INDEX IDX_2554EDA9E671FFEE ON redoublements1');
        $this->addSql('DROP INDEX IDX_2554EDA95ECD988B ON redoublements1');
        $this->addSql('ALTER TABLE redoublements1 DROP niveau_id, DROP scolarite1_id, DROP scolarite2_id, DROP scolarite3_id');
        $this->addSql('ALTER TABLE redoublements2 DROP FOREIGN KEY FK_BC5DBC13B3E9C81');
        $this->addSql('ALTER TABLE redoublements2 DROP FOREIGN KEY FK_BC5DBC136D13ADFD');
        $this->addSql('ALTER TABLE redoublements2 DROP FOREIGN KEY FK_BC5DBC13F4C45000');
        $this->addSql('ALTER TABLE redoublements2 DROP FOREIGN KEY FK_BC5DBC13E671FFEE');
        $this->addSql('ALTER TABLE redoublements2 DROP FOREIGN KEY FK_BC5DBC135ECD988B');
        $this->addSql('DROP INDEX IDX_BC5DBC13B3E9C81 ON redoublements2');
        $this->addSql('DROP INDEX IDX_BC5DBC136D13ADFD ON redoublements2');
        $this->addSql('DROP INDEX IDX_BC5DBC13F4C45000 ON redoublements2');
        $this->addSql('DROP INDEX IDX_BC5DBC13E671FFEE ON redoublements2');
        $this->addSql('DROP INDEX IDX_BC5DBC135ECD988B ON redoublements2');
        $this->addSql('ALTER TABLE redoublements2 DROP niveau_id, DROP redoublement1_id, DROP scolarite1_id, DROP scolarite2_id, DROP scolarite3_id');
        $this->addSql('ALTER TABLE regions DROP FOREIGN KEY FK_A26779F3B03A8386');
        $this->addSql('ALTER TABLE regions DROP FOREIGN KEY FK_A26779F3896DBBDE');
        $this->addSql('DROP INDEX IDX_A26779F3B03A8386 ON regions');
        $this->addSql('DROP INDEX IDX_A26779F3896DBBDE ON regions');
        $this->addSql('ALTER TABLE regions DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE santes DROP FOREIGN KEY FK_C1A17FE9A6CC7B2');
        $this->addSql('ALTER TABLE santes DROP FOREIGN KEY FK_C1A17FE9B03A8386');
        $this->addSql('ALTER TABLE santes DROP FOREIGN KEY FK_C1A17FE9896DBBDE');
        $this->addSql('DROP INDEX IDX_C1A17FE9A6CC7B2 ON santes');
        $this->addSql('DROP INDEX IDX_C1A17FE9B03A8386 ON santes');
        $this->addSql('DROP INDEX IDX_C1A17FE9896DBBDE ON santes');
        $this->addSql('ALTER TABLE santes DROP eleve_id, DROP created_by_id, DROP updated_by_id, DROP maladie, DROP medecin, DROP numero_urgence, DROP centre_sante, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE ninas DROP FOREIGN KEY FK_51AD1AF2B03A8386');
        $this->addSql('ALTER TABLE ninas DROP FOREIGN KEY FK_51AD1AF2896DBBDE');
        $this->addSql('DROP INDEX IDX_51AD1AF2B03A8386 ON ninas');
        $this->addSql('DROP INDEX IDX_51AD1AF2896DBBDE ON ninas');
        $this->addSql('ALTER TABLE ninas DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE niveaux DROP FOREIGN KEY FK_56F771A05EC1162');
        $this->addSql('ALTER TABLE niveaux DROP FOREIGN KEY FK_56F771A0B03A8386');
        $this->addSql('ALTER TABLE niveaux DROP FOREIGN KEY FK_56F771A0896DBBDE');
        $this->addSql('DROP INDEX IDX_56F771A05EC1162 ON niveaux');
        $this->addSql('DROP INDEX IDX_56F771A0B03A8386 ON niveaux');
        $this->addSql('DROP INDEX IDX_56F771A0896DBBDE ON niveaux');
        $this->addSql('ALTER TABLE niveaux DROP cycle_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE scolarites1 DROP FOREIGN KEY FK_328D2B44B3E9C81');
        $this->addSql('DROP INDEX IDX_328D2B44B3E9C81 ON scolarites1');
        $this->addSql('ALTER TABLE scolarites1 DROP niveau_id, DROP scolarite, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE scolarites2 DROP FOREIGN KEY FK_AB847AFEF4C45000');
        $this->addSql('ALTER TABLE scolarites2 DROP FOREIGN KEY FK_AB847AFEB3E9C81');
        $this->addSql('DROP INDEX IDX_AB847AFEF4C45000 ON scolarites2');
        $this->addSql('DROP INDEX IDX_AB847AFEB3E9C81 ON scolarites2');
        $this->addSql('ALTER TABLE scolarites2 DROP scolarite1_id, DROP niveau_id, DROP scolarite, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE scolarites3 DROP FOREIGN KEY FK_DC834A68B3E9C81');
        $this->addSql('DROP INDEX IDX_DC834A68B3E9C81 ON scolarites3');
        $this->addSql('ALTER TABLE scolarites3 DROP niveau_id, DROP scolarite, DROP created_at, DROP updated_at');
        $this->addSql('ALTER TABLE noms CHANGE designation designation VARCHAR(60) NOT NULL');
        $this->addSql('ALTER TABLE statuts DROP FOREIGN KEY FK_403505E6B3E9C81');
        $this->addSql('ALTER TABLE statuts DROP FOREIGN KEY FK_403505E6B03A8386');
        $this->addSql('ALTER TABLE statuts DROP FOREIGN KEY FK_403505E6896DBBDE');
        $this->addSql('DROP INDEX IDX_403505E6B3E9C81 ON statuts');
        $this->addSql('DROP INDEX IDX_403505E6B03A8386 ON statuts');
        $this->addSql('DROP INDEX IDX_403505E6896DBBDE ON statuts');
        $this->addSql('ALTER TABLE statuts DROP niveau_id, DROP created_by_id, DROP updated_by_id, DROP designation, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE telephones DROP FOREIGN KEY FK_6FCD09FB03A8386');
        $this->addSql('ALTER TABLE telephones DROP FOREIGN KEY FK_6FCD09F896DBBDE');
        $this->addSql('DROP INDEX IDX_6FCD09FB03A8386 ON telephones');
        $this->addSql('DROP INDEX IDX_6FCD09F896DBBDE ON telephones');
        $this->addSql('ALTER TABLE telephones DROP created_by_id, DROP updated_by_id, DROP numero, DROP created_at, DROP updated_at, DROP slug');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9C8121CE9');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E958819F9E');
        $this->addSql('DROP INDEX IDX_1483A5E9C8121CE9 ON users');
        $this->addSql('DROP INDEX IDX_1483A5E958819F9E ON users');
        $this->addSql('ALTER TABLE users DROP nom_id, DROP prenom_id, DROP reset_token, CHANGE fullname fullname VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE parents DROP FOREIGN KEY FK_FD501D6A3FD73900');
        $this->addSql('ALTER TABLE parents DROP FOREIGN KEY FK_FD501D6A39DEC40E');
        $this->addSql('ALTER TABLE parents DROP FOREIGN KEY FK_FD501D6AB03A8386');
        $this->addSql('ALTER TABLE parents DROP FOREIGN KEY FK_FD501D6A896DBBDE');
        $this->addSql('DROP INDEX IDX_FD501D6A3FD73900 ON parents');
        $this->addSql('DROP INDEX IDX_FD501D6A39DEC40E ON parents');
        $this->addSql('DROP INDEX IDX_FD501D6AB03A8386 ON parents');
        $this->addSql('DROP INDEX IDX_FD501D6A896DBBDE ON parents');
        $this->addSql('ALTER TABLE parents DROP pere_id, DROP mere_id, DROP created_by_id, DROP updated_by_id, DROP created_at, DROP updated_at');
    }
}
